import 'package:aula_01/models/signo.dart';

class SignosRepository {
  static List<Signo> listarTodos = [
    Signo(
      icone: 'images/aries.svg',
      nome: 'Áries',
      casa: '01',
      elemento: 'Fogo',
      raw: ['fogo', 'aries', '01'],
      preco: 10.4,
    ),
    Signo(
      icone: 'images/touro.svg',
      nome: 'Touro',
      casa: '02',
      elemento: 'Terra',
      raw: ['terra', 'touro', '02'],
      preco: 80.3,
    ),
    Signo(
      icone: 'images/gemeos.svg',
      nome: 'Gêmeos',
      casa: '03',
      elemento: 'Ar',
      raw: ['ar', 'gemeos', '03'],
      preco: 56.383,
    ),
    Signo(
      icone: 'images/cancer.svg',
      nome: 'Câncer',
      casa: '04',
      elemento: 'Água',
      raw: ['agua', 'cancer', '04'],
      preco: 00.83633,
    ),
    Signo(
      icone: 'images/leao.svg',
      nome: 'Leão',
      casa: '05',
      elemento: 'Fogo',
      raw: ['fogo', 'leao', '05'],
      preco: 02.029282,
    ),
    Signo(
      icone: 'images/virgem.svg',
      nome: 'Vírgem',
      casa: '06',
      elemento: 'Terra',
      raw: ['terra', 'virgem', '06'],
      preco: 29.39,
    ),
    Signo(
      icone: 'images/libra.svg',
      nome: 'Libra',
      casa: '07',
      elemento: 'Ar',
      raw: ['ar', 'libra', '07'],
      preco: 39.120,
    ),
    Signo(
      icone: 'images/escorpiao.svg',
      nome: 'Escorpião',
      casa: '08',
      elemento: 'Água',
      raw: ['agua', 'escorpiao', '08'],
      preco: 10.40,
    ),
    Signo(
      icone: 'images/sagitario.svg',
      nome: 'Sagitário',
      casa: '09',
      elemento: 'Fogo',
      raw: ['fogo', 'sagitario', '09'],
      preco: 22.44,
    ),
    Signo(
      icone: 'images/capricornio.svg',
      nome: 'Capricórnio',
      casa: '10',
      elemento: 'Terra',
      raw: ['terra', 'capricornio', '10'],
      preco: 29.33,
    ),
    Signo(
      icone: 'images/aquario.svg',
      nome: 'Aquário',
      casa: '11',
      elemento: 'Ar',
      raw: ['ar', 'aquario', '11'],
      preco: 09.20,
    ),
    Signo(
      icone: 'images/peixes.svg',
      nome: 'Peixes',
      casa: '12',
      elemento: 'Água',
      raw: ['agua', 'peixes', '12'],
      preco: 20.20,
    )
  ];
}
